img_size: 128
beta: 1.
latent_dim: 128
z_dim: 128
lr: 0.0001
batch_size: 64
test_seed: 1923
train_seed: 42
n_workers: 8
dropout: 0.2
accumulate_grad_batches: 1
max_epochs: 300
weight_decay: 0.
gradient_clip_val: 1e-3
