img_size: 500
beta: 4.
latent_dim: 128
lr: 0.0005
batch_size: 64
test_seed: 1923
train_seed: 42
n_workers: 8
dropout: 0.3
accumulate_grad_batches: 1
max_epochs: 50
encoding_imgsize: 2
encoding_filters: 256
weight_decay: 1e-5
gradient_clip_val: 1e-2
